# Change these first
owner: appdesign1987 # Your GitHub organization or username, where this repository lives
repo: uptimesite # The name of this repository

sites:
  - name: Nedcomp.nl
    url: https://www.nedcomp.nl
  - name: drv.nl
    url: https://drv.nl
  - name: Jeroenvd.nl
    url: https://jeroenvd.nl

  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptimesite
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** for website/webservices"
# introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
   - title: Status
     href: /
   - title: GitHub
     href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/30 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 18 5 *"
  updateTemplate: "0 0 18 5 *"
  updates: "0 3 * * *"
  uptime: "0 0 18 5 *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
